# Generated by Django 6.0.6 on 2026-06-12 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plateforme', models.CharField(default='e-Signification Bénin', max_length=100)),
                ('pays', models.CharField(default='Bénin', max_length=100)),
                ('langue_defaut', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=5)),
                ('article_loi_signification', models.TextField(blank=True)),
                ('decret_reference', models.TextField(blank=True)),
                ('nom_autorite_tutelle', models.CharField(blank=True, max_length=200)),
                ('delai_relance_1_jours', models.IntegerField(default=3)),
                ('delai_relance_2_jours', models.IntegerField(default=6)),
                ('methode_2fa_defaut', models.CharField(choices=[('email', 'Email'), ('otp', 'SMS OTP'), ('totp', 'Authenticator')], default='email', max_length=10)),
                ('copyright_texte', models.CharField(default='© e-Signification Bénin', max_length=200)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telephone_contact', models.CharField(blank=True, max_length=20)),
                ('adresse_contact', models.TextField(blank=True)),
                ('certigna_active', models.BooleanField(default=False)),
                ('certigna_tsa_url', models.URLField(blank=True, default='https://tsa.certigna.fr/tsa')),
                ('certigna_login', models.CharField(blank=True, max_length=100)),
                ('certigna_password_chiffre', models.CharField(blank=True, max_length=500)),
                ('certigna_oid', models.CharField(blank=True, max_length=100)),
                ('certigna_heure_lot', models.TimeField(default='00:00')),
                ('certigna_seuil_alerte_jetons', models.IntegerField(default=20)),
                ('certigna_jetons_restants', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Configuration plateforme',
            },
        ),
        migrations.CreateModel(
            name='LotMerkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_lot', models.DateField(unique=True)),
                ('hash_racine', models.CharField(max_length=64)),
                ('jeton_certigna', models.BinaryField(blank=True, null=True)),
                ('nb_actes_couverts', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('certifie', 'Certifié par Certigna'), ('local', 'Horodatage local uniquement')], default='en_attente', max_length=20)),
            ],
            options={
                'verbose_name': 'Lot Merkle',
                'ordering': ['-date_lot'],
            },
        ),
        migrations.CreateModel(
            name='ModeleEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_email', models.CharField(choices=[('activation_huissier', 'Activation compte huissier'), ('invitation_justiciable', 'Invitation justiciable'), ('confirmation_domicile', 'Confirmation domicile électronique'), ('signification_envoyee', 'Signification envoyée'), ('relance_1', 'Relance 1'), ('relance_2', 'Relance 2'), ('reponse_recue', 'Réponse reçue'), ('certificat_genere', 'Certificat généré'), ('recuperation_mdp', 'Récupération mot de passe'), ('alerte_jetons', 'Alerte jetons Certigna')], max_length=50)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], max_length=5)),
                ('sujet', models.CharField(max_length=200)),
                ('corps_html', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Modèle d'email",
                'unique_together': {('type_email', 'langue')},
            },
        ),
        migrations.CreateModel(
            name='PisteAudit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(max_length=100)),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('objet_uuid', models.CharField(blank=True, max_length=36)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Piste d'audit",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TexteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_texte', models.CharField(choices=[('cgu', "Conditions Générales d'Utilisation"), ('mentions', 'Mentions légales'), ('confidentialite', 'Politique de confidentialité')], max_length=20)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], max_length=5)),
                ('titre', models.CharField(max_length=200)),
                ('contenu_html', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Texte légal',
                'unique_together': {('type_texte', 'langue')},
            },
        ),
    ]
