# Generated by Django 5.2.13 on 2026-06-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_acceptation_texte_legal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='acceptationtextelegal',
            new_name='administrat_user_id_62825c_idx',
            old_name='administrat_user_id_6f0a0d_idx',
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='credit_signification_annulee',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Coût net si annulation (remboursement = débit − ce montant)', max_digits=6),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='credit_signification_refusee',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Coût net si le justiciable refuse (remboursement = débit − ce montant)', max_digits=6),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='credit_signification_reussie',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Crédit débité à l'envoi (et conservé si le justiciable accepte)", max_digits=6),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='kkiapay_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='kkiapay_private_key_chiffre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='kkiapay_public_key_chiffre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='kkiapay_sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='kkiapay_secret_chiffre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='prix_credit_fcfa',
            field=models.PositiveIntegerField(default=2000, help_text="Prix d'achat d'un crédit en FCFA"),
        ),
    ]
