# Generated by Django 5.2.13 on 2026-06-30 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('huissiers', '0003_profilhuissier_solde_credits'),
        ('significations', '0006_signification_credit_ajuste_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nb_credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_fcfa', models.PositiveIntegerField()),
                ('transaction_kkiapay', models.CharField(blank=True, db_index=True, max_length=120)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complétée'), ('echoue', 'Échouée')], default='en_attente', max_length=20)),
                ('reference_client', models.CharField(blank=True, db_index=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('huissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_credits', to='huissiers.profilhuissier')),
            ],
            options={
                'verbose_name': 'Commande de crédits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type_mouvement', models.CharField(choices=[('achat', 'Achat'), ('gratuit', 'Attribution gratuite'), ('consommation', 'Débit signification'), ('remboursement', 'Retour crédit (réponse client)'), ('ajustement', 'Ajustement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Positif = crédit ajouté, négatif = crédit consommé', max_digits=10)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='paiements.commandecredit')),
                ('huissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_credits', to='huissiers.profilhuissier')),
                ('signification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_credits', to='significations.signification')),
            ],
            options={
                'verbose_name': 'Mouvement de crédit',
                'ordering': ['-date'],
            },
        ),
    ]
