# Generated by Django 6.0.6 on 2026-06-12 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilHuissier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nom_etude', models.CharField(max_length=200)),
                ('ifu', models.CharField(blank=True, max_length=50, verbose_name='Numéro IFU')),
                ('npi', models.CharField(blank=True, max_length=50, verbose_name='Numéro NPI')),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', "En attente d'activation")], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_huissier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil huissier',
            },
        ),
        migrations.CreateModel(
            name='ProfilClerc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_clerc', to=settings.AUTH_USER_MODEL)),
                ('huissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clercs', to='huissiers.profilhuissier')),
            ],
            options={
                'verbose_name': 'Clerc assermenté',
            },
        ),
    ]
