# Generated by Django 5.2.13 on 2026-06-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huissiers', '0002_parametresignaturehuissier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilhuissier',
            name='solde_credits',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde de crédits disponibles pour les significations', max_digits=12),
        ),
    ]
