# Generated by Django 6.0.6 on 2026-06-12 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('huissier', 'Huissier de justice'), ('clerc', 'Clerc assermenté'), ('justiciable', 'Justiciable')], default='justiciable', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('mfa_methode', models.CharField(choices=[('email', 'Code par email'), ('otp', 'Code SMS (OTP)'), ('totp', 'Application authentificateur (TOTP)')], default='email', max_length=10)),
                ('mfa_active', models.BooleanField(default=True)),
                ('totp_secret', models.CharField(blank=True, max_length=32)),
                ('mfa_code', models.CharField(blank=True, max_length=6)),
                ('mfa_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='TokenActivation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('type_token', models.CharField(choices=[('activation_huissier', 'Activation huissier'), ('invitation_justiciable', 'Invitation justiciable'), ('recuperation_mdp', 'Récupération mot de passe'), ('confirmation_email', 'Confirmation email'), ('mfa_code', 'Code MFA')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('utilise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Token d'activation",
                'ordering': ['-date_creation'],
            },
        ),
    ]
