# Generated by Django 5.2.13 on 2026-06-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenactivation',
            name='type_token',
            field=models.CharField(choices=[('activation_huissier', 'Activation huissier'), ('invitation_justiciable', 'Invitation justiciable'), ('recuperation_mdp', 'Récupération mot de passe'), ('confirmation_email', 'Confirmation email'), ('mfa_code', 'Code MFA'), ('changement_email_domicile', 'Changement email domicile'), ('activation_clerc', 'Activation clerc')], max_length=30),
        ),
    ]
