# Generated by Django 6.0.6 on 2026-06-12 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('huissiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilJusticiable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type_compte', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nom_entreprise', models.CharField(blank=True, max_length=200)),
                ('ifu', models.CharField(blank=True, max_length=50, verbose_name='Numéro IFU')),
                ('npi', models.CharField(blank=True, max_length=50, verbose_name='Numéro NPI')),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email_domicile', models.EmailField(max_length=254, verbose_name="Email d'élection de domicile électronique")),
                ('email_domicile_verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_justiciable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil justiciable',
            },
        ),
        migrations.CreateModel(
            name='InvitationJusticiable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email_cible', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('utilise', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('huissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to='huissiers.profilhuissier')),
                ('justiciable_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='justiciables.profiljusticiable')),
            ],
            options={
                'verbose_name': 'Invitation justiciable',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
