# Generated by Django 6.0.6 on 2026-06-12 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('huissiers', '0001_initial'),
        ('justiciables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('fichier_chiffre', models.BinaryField(blank=True, null=True)),
                ('nom_fichier_original', models.CharField(blank=True, max_length=255)),
                ('taille_fichier', models.IntegerField(default=0)),
                ('necessite_reponse', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('relance_1', 'Relance 1'), ('relance_2', 'Relance 2'), ('non_delivree', 'Non délivrée électroniquement'), ('traditionnelle', 'Bascule signification traditionnelle'), ('repondu', 'Réponse reçue')], default='en_attente', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_refus', models.DateTimeField(blank=True, null=True)),
                ('date_horodatage_envoi', models.DateTimeField(blank=True, null=True)),
                ('hash_acte', models.CharField(blank=True, max_length=64)),
                ('hash_merkle_position', models.IntegerField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='significations_envoyees', to=settings.AUTH_USER_MODEL)),
                ('huissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='significations', to='huissiers.profilhuissier')),
                ('justiciable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='significations_recues', to='justiciables.profiljusticiable')),
            ],
            options={
                'verbose_name': 'Signification',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ReponseJusticiable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fichier_reponse_chiffre', models.BinaryField(blank=True, null=True)),
                ('nom_fichier_reponse', models.CharField(blank=True, max_length=255)),
                ('date_envoi_justiciable', models.DateTimeField(auto_now_add=True)),
                ('date_reception_huissier', models.DateTimeField(blank=True, null=True)),
                ('hash_reponse', models.CharField(blank=True, max_length=64)),
                ('vue_par_huissier', models.BooleanField(default=False)),
                ('signification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reponse', to='significations.signification')),
            ],
            options={
                'verbose_name': 'Réponse justiciable',
            },
        ),
        migrations.CreateModel(
            name='CertificatSignification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_reception', models.DateTimeField()),
                ('timezone_reception', models.CharField(default='Africa/Porto-Novo', max_length=50)),
                ('hash_certificat', models.CharField(max_length=64)),
                ('hash_merkle', models.CharField(blank=True, max_length=64)),
                ('chemin_merkle', models.JSONField(blank=True, default=list)),
                ('horodatage_certigna', models.BinaryField(blank=True, null=True)),
                ('fichier_certificat_chiffre', models.BinaryField(blank=True, null=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('lot_merkle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.lotmerkle')),
                ('signification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificat', to='significations.signification')),
            ],
            options={
                'verbose_name': 'Certificat de signification',
            },
        ),
        migrations.CreateModel(
            name='RelanceSignification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_relance', models.IntegerField(choices=[(1, 'Relance 1'), (2, 'Relance 2')])),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('constat_chiffre', models.BinaryField(blank=True, null=True)),
                ('signification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='significations.signification')),
            ],
            options={
                'verbose_name': 'Relance',
                'unique_together': {('signification', 'numero_relance')},
            },
        ),
    ]
