# Generated by Django 5.2.13 on 2026-06-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('significations', '0003_yousign_signification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signification',
            name='statut',
            field=models.CharField(choices=[('attente_signature', 'En attente de signature huissier'), ('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('relance_1', 'Relance 1'), ('relance_2', 'Relance 2'), ('non_delivree', 'Non délivrée électroniquement'), ('traditionnelle', 'Bascule signification traditionnelle'), ('repondu', 'Réponse reçue')], default='en_attente', max_length=20),
        ),
    ]
