# Generated by Django 5.2.13 on 2026-06-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('significations', '0005_yousign_audit_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='signification',
            name='credit_ajuste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signification',
            name='credit_debite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='signification',
            name='statut',
            field=models.CharField(choices=[('attente_signature', 'En attente de signature huissier'), ('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('relance_1', 'Relance 1'), ('relance_2', 'Relance 2'), ('non_delivree', 'Non délivrée électroniquement'), ('traditionnelle', 'Bascule signification traditionnelle'), ('repondu', 'Réponse reçue'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
